### ISSUE TITLE
翻译的最终收尾工作 🎉

### ISSUE THREAD

**Issue by butterunderflow** [butterunderflow/rescript-lang.org-chinese-translation#44]
在大家的共同努力下, ReScript 语言手册的中文文档的翻译和校对工作已经初步完成了. 这里要感谢[翻译](https://github.com/butterunderflow/rescript-lang.org-chinese-translation/issues/2)/[校对](https://github.com/butterunderflow/rescript-lang.org-chinese-translation/issues/3)小队每一位同学的帮助, ReScript的推广普及离不开你们的共同支持! 🤝

在这里要特别感谢 [include-yy](https://github.com/include-yy) 同学, 日夜兼程完成了绝大部分的校对工作(大佬注意休息🌙). 接下来 [include-yy](https://github.com/include-yy) 将继续进行全文的最终检查和风格统一工作, 还请大家短时间内不要发起PR. 如果有任何问题请随时发起issue或者在微信沟通, 再次感谢大家的帮助❤

**Comment by include-yy** [comment]
已完成。

**Comment by butterunderflow** [comment]
十分感谢你的帮助! 辛苦了
